"""create users and messages tables

Revision ID: 7c8bf9b4f48b
Revises:
Create Date: 2026-06-28 08:08:46.509783

"""

from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = "7c8bf9b4f48b"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
